restore part

diff --git a/cpd/cpd-bp.yaml b/cpd/cpd-bp.yaml
--- a/cpd/cpd-bp.yaml
+++ b/cpd/cpd-bp.yaml
@@ -222,3 +222,58 @@ actions:
             echo "Deleting the tenant backup"
             echo "============================================================================"
             cpd-cli oadp tenant-backup delete $TENANT_BACKUP_NAME
+  restore:
+    inputArtifactNames:
+    - cpdOutput
+    phases:
+    - func: KubeTask
+      name: restoreSchedulingBackupAndTenantBackup
+      args:
+        image: michaelcourcy/kasten-cpd:k108.0.2-cpd5.1.x        
+        command:
+          - bash
+          - -o
+          - errexit
+          - -o
+          - pipefail
+          - -x
+          - -c
+          - |   
+            
+            echo "applying cpd-vars defined in the secret"
+            {{- range $key, $value := .Phases.backupSchedulingAndTenant.Secrets.cpdVars.Data }}
+            export {{ $key }}={{ $value | toString }}
+            {{- end }} 
+
+            echo "checking cpd-cli is working properly"
+            export HOME=/tmp
+            cd /tmp/
+            cpd-cli oadp client config set namespace=$OADP_PROJECT
+
+            SCHEDULING_BACKUP_NAME='{{ .ArtifactsIn.cpdOutput.KeyValue.schedulingBackupName }}'
+            TENANT_BACKUP_NAME='{{ .ArtifactsIn.cpdOutput.KeyValue.tenantBackupName }}'
+
+            # control that namespace $PROJECT_CPD_INST_OPERANDS, $PROJECT_CPD_INST_OPERATORS and $PROJECT_SCHEDULING_SERVICE are deleted
+            # otherwise the restore will fail
+            if kubectl get namespace $PROJECT_CPD_INST_OPERANDS; then
+              echo "Namespace $PROJECT_CPD_INST_OPERANDS still exists, please delete it before restoring "
+              exit 1
+            fi
+            if kubectl get namespace $PROJECT_CPD_INST_OPERATORS; then
+              echo "Namespace $PROJECT_CPD_INST_OPERATORS still exists, please delete it before restoring "
+              exit 1
+            fi
+            if kubectl get namespace $PROJECT_SCHEDULING_SERVICE; then
+              echo "Namespace $PROJECT_SCHEDULING_SERVICE still exists, please delete it before restoring "
+              exit 1
+            fi
+
+            echo "============================================================================"
+            echo "Deleting the scheduling service backup"
+            echo "============================================================================"
+            cpd-cli oadp backup delete $SCHEDULING_BACKUP_NAME
+
+            echo "============================================================================"
+            echo "Deleting the tenant backup"
+            echo "============================================================================"
+            cpd-cli oadp tenant-backup delete $TENANT_BACKUP_NAME
